name:                AdventUtil
version:             0.1.0.0
github:              "kevorr/programming-challenges"
author:              "Kevin Orr"

extra-source-files: []

default-extensions:
  - ViewPatterns
  - TypeApplications

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: []

tests:
  AdventUtil-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventUtil
    - hspec
    - hspec-expectations-pretty-diff
