name:                Advent2017
version:             0.1.0.0
github:              "kevorr/programming-challenges"
author:              "Kevin Orr"

extra-source-files: []

default-extensions:
  - ViewPatterns
  - TypeApplications

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: []

executables:
  2017:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Advent2017

tests:
  Advent2017-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Advent2017
    - hspec
    - hspec-expectations-pretty-diff
